<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [

        realpath(app_path('Providers/AppServiceProvider.php')),
        realpath(app_path('Providers/BusServiceProvider.php')),
        realpath(app_path('Providers/ConfigServiceProvider.php')),
        realpath(app_path('Providers/EventServiceProvider.php')),
        realpath(app_path('Providers/ExtensionServiceProvider.php')),
        realpath(app_path('Providers/RouteServiceProvider.php')),

    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled Config Files
    |--------------------------------------------------------------------------
    |
    | Here you may list config namespace/file which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'config' => [
        //
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
